### ISSUE TITLE
port config is ignored

### ISSUE THREAD

**Issue by marcboscher** [logstash-plugins/logstash-input-elasticsearch#11]
Although the doc lists a "port" option, it looks like it is ignored entirely by the input.
Using logstash 1.5.0 RC2

Can suffix the hosts config with `:port` but only works for http, not https

For example
hosts => ["myhost:9243"]
post => 9243
ssl => true

The error reported is:
  the scheme https does not accept registry part: my-host:9243:9200 (or bad hostname?)

**Comment by jordansissel** [comment]
I think attempting to specify a port in the `host` field and separately as a `port` setting should be a config validation error. We can make that happen.

**Comment by marcboscher** [comment]
seems to me if I specifie the port config and leave the port out of the
hosts config, the default port 9200 is used. In other words, the port
config is ignored.

**Comment by jsvd** [comment]
having multiple hosts in the :hosts config makes the port setting awkward to use, it limits your ability to use it for lists like:  `host1:9200 host2:9201 host3:9203``

in #17 I suggest removing the port setting completely and using "host:port" by default. I'll also submit a pr for fixing https handling

**Comment by magnusbaeck** [comment]
The change described by @jsvd was implemented long ago and the `port` no longer exists so this issue can be closed.
