### ISSUE TITLE
support proxy => ... configuration

### ISSUE THREAD

**Issue by kares** [logstash-plugins/logstash-input-elasticsearch#113]
ES input (and possibly filter) should support `proxy` like in ES output plugin does

HINT: an empty proxy configuration `proxy => ''` should act as if no proxy was set

previous feature requests #67 and #41

**Comment by andsel** [comment]
I think that empty string could be source of some misunderstanding, perhaps an explicit value as `"no proxy"` or `false` could be more helpful in reading the config.

**Comment by kares** [comment]
thanks for the feedback. might sound weird at first but libraries work that way 
e.g. `export http_proxy=""` is pretty much ignored by all network utilities ...

we also do have the feature now in ES output: https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/912
