### ISSUE TITLE
Explicitly close the scroll

### ISSUE THREAD

**Issue by strawgate** [logstash-plugins/logstash-input-elasticsearch#122]
The Elasticsearch Input creates a scroll for the request and expects the scroll to timeout to close it. It would be nice if there was an option so that when Logstash reaches the end of the scroll it explicitly closes the scroll instead of waiting for the timeout.

**Comment by colinsurprenant** [comment]
Thanks @strawgate for the heads up.
Fixed with #128 and available in v4.6.2.
