### ISSUE TITLE
Use "search_after" instead of "scroll"

### ISSUE THREAD

**Issue by toby-sutor** [logstash-plugins/logstash-input-elasticsearch#163]
The [Elasticsearch scroll API](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/scroll-api.html) discourages the use of the `scroll` API since version 7.10 in favor of the [search_after](https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#search-after) parameter.

I think it would be great if the `search_after` approach could be incorporated in the `Elasticsearch input plugin`.

**Comment by kaisecheng** [comment]
use the `search_after` parameter with a point in time (PIT) to replace `scroll`
