### ISSUE TITLE
Results from all scrolls for each slice are stored in memory leading to OOM

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-input-elasticsearch#188]
In [PR#179](https://github.com/logstash-plugins/logstash-input-elasticsearch/pull/179), a [temporary array](https://github.com/logstash-plugins/logstash-input-elasticsearch/pull/179/files#diff-04cb591df2446500a108eebbfe57c8ed0c72553d33abe1bcef68a5a15474b097R325-R327) is used to store the results for each slice.
For each slice, the multiple scrolls are executed and stored in the array, leading to OOM.

**Comment by kaisecheng** [comment]
this issue is fixed in `4.17.1`
