### ISSUE TITLE
Add `x-elastic-product-origin` header to all places that make requests to Elasticsearch

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-input-elasticsearch#212]
The Logstash Elasticsearch input plugin makes HTTP requests to the following Elasticsearch endpoints:

```
GET /
HEAD /
POST /index/_pit
POST /_search?size=
POST /_search?scroll=
POST /index/_search?scroll=
DELETE /_pit
DELETE /_search/scroll
```

Each of these calls should include the x-elastic-internal-origin header to the HTTP request made to Elasticsearch

**Comment by robbavey** [comment]
Updated to correct the header name to `x-elastic-product-origin`

**Comment by donoghuc** [comment]
Released in https://github.com/logstash-plugins/logstash-input-elasticsearch/releases/tag/v4.20.5
