### ISSUE TITLE
refactor shutdown sequence to use plugin.stop

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-input-elasticsearch#29]
Change shutdown sequence to be triggered by plugin.stop instead of ShutdownSignal exception.
Also remove any calls to: shutdown, finished, finished?, running? or terminating?
This depends on https://github.com/elastic/logstash/pull/3895

**Comment by purbon** [comment]
Fixed in #28

**Comment by jsvd** [comment]
closed by https://github.com/logstash-plugins/logstash-input-elasticsearch/pull/28
