### ISSUE TITLE
Typo in example s/host/hosts

### ISSUE THREAD

**Issue by Semyazz** [logstash-plugins/logstash-input-elasticsearch#30]
There is a typo in Example section, but it looks like the source is correct, so probably it was not re-generated.

```
input {
  # Read all documents from Elasticsearch matching the given query
  elasticsearch {
    host => "localhost"
    query => '{ "query": { "match": { "statuscode": 200 } } }'
  }
}
```

`host` should be changed to `hosts`

**Comment by magnusbaeck** [comment]
This was fixed in commit 876d7988ed51272950985e208b6abb571f797fbb so this issue can be closed.
