### ISSUE TITLE
Disable ssl certificate validation

### ISSUE THREAD

**Issue by robin13** [logstash-plugins/logstash-input-elasticsearch#33]
Would be good to have the same option which is available for logstash-output-elasticsearch to be able to disable ssl certificate verification:

[ssl_certificate_verification: false](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-ssl_certificate_verification)

**Comment by damianpfister** [comment]
+1

**Comment by RichJackson** [comment]
+1

**Comment by c2pigisme** [comment]
+1

**Comment by michalterbert** [comment]
+1

**Comment by jscotthead** [comment]
+1

**Comment by jordansissel** [comment]
Please stop commenting "+1". Doing so generates tons of emails. I have deleted all the +1 comments. At the time of deletion, there were 5 +1 comments.

Related: We don't have a voting system.

**Comment by bw498c** [comment]
Original comment was in 2015. Is there an ETA for this?

**Comment by rlwmmw** [comment]
This is an absolute necessity.  When using ECE, The auto-generated, self-signed certs do not match the host-name, and adding certs to a ca_file doesn't resolve this issue.  A no-verify option is basic and should be included.

**Comment by ageis** [comment]
Is such an option available for the Logstash input? I've been using Easy-RSA to generate my own self-signed certs via my own CA, which I then propagate to the server and Filebeat/Metricbeat clients and I still run into lots of problems...

**Comment by rkhapre** [comment]
Hi, i have replace the file above with the existing file and it is still not working
This is how my conf file looks like

```
input {
  elasticsearch {
    hosts => ["acd.com:9200"]
	ssl => false
	user => "xyz"
	password => "psw"
    index => "asdfg"
    size => 10
    #scroll => "5m"
    docinfo => true
  }
}
```

I am getting this error

```
docinfo_fields=>["_index", "_type", "_id"], ssl_certificate_verification=>tr
ue>
  Error: certificate verify failed
  Exception: Faraday::SSLError
  Stack: org/jruby/ext/openssl/SSLSocket.java:215:in `connect'
```

Let me know , how you resolved it

**Comment by tomryanx** [comment]
In case anyone else gets here looking for an answer to the question asked by @rkhapre - the code above adds a configuration option `ssl_certificate_verification` which defaults to `true`. To disable, add the following line to the elasticsearch input in logstash config:

```
ssl_certificate_verification => false
```

**Comment by turbopape** [comment]
Hello, I added this setup but still getting an error:
 my conf:
output {
      elasticsearch {
          hosts => "https://XYZ:9200"
          user => "XYZ"
          password =>"XYZ"
          ssl_certificate_verification => false 
      }
The error:
[WARN ] 2020-08-04 20:26:59.294 [Ruby-0-Thread-5: /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.5.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:241] elasticsearch - Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"https://XYZ:XYZ@XYZ:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: ["https://XYZ:XYZ@XYZ:9200/][Manticore::ClientProtocolException] PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"}

**Comment by rafzei** [comment]
@turbopape from error log above I see that you are using output plugin.
Put one more line `ssl => true`
and remove protocol from hosts, leave just `host:ip`

In case of input and missing skipping cert validation, the easy workaround is:
in `elasticsearch.rb` add new line:
`ssl_options[:verify] = false`
right after
```
hosts = setup_hosts
ssl_options = setup_ssl
```

**Comment by turbopape** [comment]
Hey rafzei, thanks for the advice 👍 I actually disabled es https altogether :)
Will try it and get back to you thanks :)

**Comment by andresff** [comment]
@ankitdevnalkar  I don't know if it's relevant my case. I was trying to connect to Elasticsearch service on AWS from within VPC EC2 Server. I tried a lot of things and finally the solution was the following:

output {
  elasticsearch {
    hosts => ["https://vpc-abxxxxxxxxxx.us-east-2.es.amazonaws.com:443"]
    index => "testindex"	
    document_id => "%{id}"
    doc_as_upsert => true
    # not necessary if running inside AWS, otherwise yes)
    ssl_certificate_verification => false
    # ilm_enabled => false this is important (if not auth error 401)
    ilm_enabled => false
 }
}

**Comment by japplewhite** [comment]
No combination of options works even on a non-AWS S3 compatible bucket like NetApp StorageGRID
setting the valid URL to an IP fails with ssl_certificate_verification => false  
valid URLs with signed certificates don't work because logstash assumes AWS S3. 
Really there is no solution for people who want to use non-AWS S3 storage?

**Comment by tomryanx** [comment]
@japplewhite I think you need to provide more info... this is specifically for the logstash `elasticsearch` `input` plugin... nothing to do with S3... if you provide more detail maybe someone can direct you to the right place

**Comment by amarga83** [comment]
> @turbopape from error log above I see that you are using output plugin.
> Put one more line `ssl => true`
> and remove protocol from hosts, leave just `host:ip`
> 
> In case of input and missing skipping cert validation, the easy workaround is:
> in `elasticsearch.rb` add new line:
> `ssl_options[:verify] = false`
> right after
> 
> ```
> hosts = setup_hosts
> ssl_options = setup_ssl
> ```
> 
> Edit: tested with logstash-oss 7.9.0 (input plugin v4.7.0)

@rafzei I tried adding the ssl_options[:verify] = false configuration to the elasticsearch.rb file. But it is still not working. I restarted the logstash service, is there anything else that I should restart in order to make it work?

Btw, my elasticsearch instance has security enabled, I enabled ssl and we are using self-signed certificates, normally when I run a curl command I pass the -k option so it ignores the certificates validation, that is why I tried setting this in the logstash pipeline:

ssl_options[:verify] = false

I am also using an api key instead of user and password.

**Comment by robertknutzen** [comment]
Users: Hey can I get this very simple option that already exists in the elasticsearch output? 
ES: No

Glad ya'll gettin forked

**Comment by douniwan5788** [comment]
@jordansissel I think people really need a "+1" for reminding that such a basic feature is 7 years old and still unsolved

**Comment by demonkit** [comment]
any updates?

**Comment by psdjc** [comment]
The function to disable ssl validation is absolutely necessary.

**Comment by mashhurs** [comment]
[`4.16.0`](https://rubygems.org/gems/logstash-input-elasticsearch/versions/4.16.0) version is out with SSL validation control feature.

**Comment by emhlbmc** [comment]
@mashhurs it works for me, thanks for your contribution 💯
