### ISSUE TITLE
Update docs to remove "port =>" config option.

### ISSUE THREAD

**Issue by n0othing** [logstash-plugins/logstash-input-elasticsearch#34]
Need to remove mention of "port =>" option from documentation. Port is now set in the hosts option #17

**Comment by jordansissel** [comment]
This should happen automatically when the next docs generator is run. I'm not familiar with that process, but maybe @suyograo or @untergeek can give it a poke?

**Comment by untergeek** [comment]
Indeed.  It will get picked up then, and not likely before.  Did we need this to be in the documentation before the next release?
