### ISSUE TITLE
Change default query to sort by _doc

### ISSUE THREAD

**Issue by shaharmor** [logstash-plugins/logstash-input-elasticsearch#38]
According to this page: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html
there is a performance improvement when using the following query on scroll:
```
{
  "sort": [
    "_doc"
  ]
}
```

We should consider changing the default query to use that

**Comment by jordansissel** [comment]
By default Logstash uses a search_type of `scan` which probably has the same or similar effect. (https://github.com/logstash-plugins/logstash-input-elasticsearch/blob/master/lib/logstash/inputs/elasticsearch.rb#L45-L47 and https://github.com/logstash-plugins/logstash-input-elasticsearch/blob/master/lib/logstash/inputs/elasticsearch.rb#L118)

Have you measured any performance differences with this change? If so, in what configurations?

**Comment by jimferenczi** [comment]
The scan search type always uses the sort by _doc optimization but watch out because this is a deprecated from ES 2.1.0. You should consider switching to a regular scroll request where the sort by "_doc" is needed to have similar performance as @shaharmor suggested.

**Comment by untergeek** [comment]
This was handled in #51
