### ISSUE TITLE
switch from scan to scroll

### ISSUE THREAD

**Issue by djschny** [logstash-plugins/logstash-input-elasticsearch#50]
- Version: v5.0.0-rc1
- Operating System: Mac 10.12

Using a simple config:
```
input { elasticsearch { index => "citibike-trips" } }
filter {}
output { stdout { codec => "rubydebug" } }
```

The following error is thrown:

```
[2016-10-12T14:52:39,634][ERROR][logstash.pipeline        ] A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::Elasticsearch index=>"citibike-trips", id=>"ca1129a233dae70a186b30f08aa829bac64b30e0-1", enable_metric=>true, codec=><LogStash::Codecs::JSON id=>"json_1d4cf6cb-7ca6-4404-a9d7-96fde965269b", enable_metric=>true, charset=>"UTF-8">, query=>"{\"query\": { \"match_all\": {} } }", scan=>true, size=>1000, scroll=>"1m", docinfo=>false, docinfo_target=>"@metadata", docinfo_fields=>["_index", "_type", "_id"], ssl=>false>
  Error: [400] {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"No search type for [scan]"}],"type":"illegal_argument_exception","reason":"No search type for [scan]"},"status":400}
```
This appears to happen because this plugin uses the `scan` search type, which was [removed in Elsaticsearch v5](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_search_changes.html#_literal_search_type_scan_literal_removed).

**Comment by untergeek** [comment]
It's not so much a switch as it is a "remove".  Scroll has always been in there, but scan was "true" by default.  I'll be removing `scan` as an option.

**Comment by djschny** [comment]
It's a few things that I can see:

* remove the `scan` option
* change that `size` is now per overall response and now per shard
* default to sorting the scroll by `_doc` which gives previous scan behavior

**Comment by untergeek** [comment]
> default to sorting the scroll by `_doc` which gives previous scan behavior

I'm not sure that's completely necessary, as Logstash users are accustomed to handling data in an asynchronous manner.  If the documents are out of order, what's the problem?  But can't that be added to the query body anyway, if desired?  Having to auto-merge that into a query would actually complicate things, I think.

> change that `size` is now per overall response and now per shard
The `now`s are confusing me. Since `size` certainly _was_ per shard, did you mean that `size` is _now_ per overall response and _not_ per shard?  Where is this change documented? I can't seem to find it.

**Comment by untergeek** [comment]
Okay, I see this:

> Scroll requests have optimizations that make them faster when the sort order is _doc. If you want to iterate over all documents regardless of the order, this is the most efficient option:

So I will add the sort by `_doc` to the default query, with documentation indicating that it should be added to other queries.

**Comment by djschny** [comment]
> I'm not sure that's completely necessary, as Logstash users are accustomed to handling data in an asynchronous manner. If the documents are out of order, what's the problem? But can't that be added to the query body anyway, if desired?

It has nothing to do with that, it is for performance (similar to what scan did).

> The nows are confusing me. Since size certainly was per shard, did you mean that size is now per overall response and not per shard?

Sorry typo on my part, the second `now` should be a `not`.

> Where is this change documented? I can't seem to find it.

I was never able to find it either, but when I've tested those have been my findings.

**Comment by untergeek** [comment]
I just found it: https://www.elastic.co/guide/en/elasticsearch/reference/5.0/search-uri-request.html

> `size` The number of hits to return. Defaults to 10.

**Comment by untergeek** [comment]
Hmmm.  It says that in older versions too. Perhaps "per shard" is implied in the older versions.

**Comment by untergeek** [comment]
Here's the answer from an internal discussion:

> `SCAN` used to be an exception: in all other cases (simple search, regular scrolls), search operations return ${size} documents per page - only `SCAN` would return ${size}x${num_shards}. So now that SCAN is gone and that we recommend to use the `_search/scroll` API and to sort by `_doc` in order to fetch all documents from an index, calls to the search API always return ${size} documents per page.

That means that `scan` is the only case where `size` was _per shard._ So, changing the documentation here shouldn't be necessary as it currently says:

```
  # This allows you to set the maximum number of hits returned per scroll.
  config :size, :validate => :number, :default => 1000
```
