### ISSUE TITLE
Add the ability to use the new Sliced Scroll feature in 5.0

### ISSUE THREAD

**Issue by geekpete** [logstash-plugins/logstash-input-elasticsearch#53]
Add the ability to use the new Sliced Scroll feature in Elasticsearch 5.0:
https://www.elastic.co/guide/en/elasticsearch/reference/5.0/search-request-scroll.html#sliced-scroll

This should result in performance improvements when scrolling out of a 5.0 ES endpoint.

If multiple Logstash instances are being used then each host could use a configuration that is pointing at a different slice of the same scroll, though coordination of this would be manual.

**Comment by jordansissel** [comment]
> If multiple Logstash instances are being used then each host could use a configuration that is pointing at 

Given Logstash has no node-to-node coordination, it seems like it would be a pretty annoying burden to require users to configure the IDs of each slice query for all nodes querying the same (making sure that `id` was not duplicated and `max` was the same on all nodes). I would feel bad delivering a feature that requires such levels of interaction :|

Maybe we can do this once Logstash has some kind of work coordination across instances.

**Comment by geekpete** [comment]
So to clarify this ticket, I am only after the plugin having the ability to switch from a serial scroll to a parallel scroll using slices. Coordinating nodes is much more complex and isn't what I was implying with this particular ticket.

There should be great benefit even from a single logstash instance running to do a parallel scroll.

This would be a new parameter the user can turn on to enable using sliced scroll and would use a sensible default # of slices. # of cores might be a good starting point to test with.

There's also the concern of too many slices creating too much overhead on the cluster and degrading performance, but we can test out some scenarios. And some benchmarks might be nice to test as well.

**Comment by geekpete** [comment]
So to clarify this ticket, I am only after the plugin having the ability to switch from a serial scroll to a parallel scroll using slices. Coordinating nodes is much more complex and isn't what I was implying with this particular ticket.

There should be great benefit even from a single logstash instance running to do a parallel scroll.

This would be a new parameter the user can turn on to enable using sliced scroll and would use a sensible default # of slices. # of cores might be a good starting point to test with.

There's also the concern of too many slices creating too much overhead on the cluster and degrading performance, but we can test out some scenarios. And some benchmarks might be nice to test as well.

**Comment by consulthys** [comment]
The `slices` option has been [introduced in Logstash 7.0.0](https://www.elastic.co/guide/en/logstash/current/logstash-7-0-0.html#_input_plugins_3).
