### ISSUE TITLE
Set Content-Type and Accept headers

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-input-elasticsearch#55]
This is necessary to support https://github.com/elastic/elasticsearch/pull/22691 when it lands. Without fixing this, this input will (likely?) not work against new Elasticsearch releases.

**Comment by jordansissel** [comment]
Blocked on https://github.com/elastic/elasticsearch-ruby/issues/400

**Comment by jordansissel** [comment]
https://github.com/logstash-plugins/logstash-input-elasticsearch/pull/56 works around it.

**Comment by karmi** [comment]
Blocking resolved in https://github.com/elastic/elasticsearch-ruby/commit/76f86793cde0a0e7e816a743c73f69002a53483e and released as https://rubygems.org/gems/elasticsearch-transport/versions/5.0.2

**Comment by karmi** [comment]
Version https://rubygems.org/gems/elasticsearch-transport/versions/5.0.3 released, which addresses a bug in the Manticore adapter when handling options.
