### ISSUE TITLE
Update docs to note that a size of -1 will return all the results from the query

### ISSUE THREAD

**Issue by ctindel** [logstash-plugins/logstash-input-elasticsearch#84]
Or we should note that omitting the size parameter will return all results from the query.

One or the other, its just that our docs don't currently answer the question of what to do if you want the full result set.

**Comment by ycombinator** [comment]
This input makes a [scroll request](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html) under the hood. Such a request will _always_ return all the results (except with `size = 0`) eventually. The `size` only pertains to how many results should be returned in each scroll (aka batch).

**Comment by ctindel** [comment]
Ah ok that makes sense, thanks.

**Comment by ycombinator** [comment]
Related: https://github.com/logstash-plugins/logstash-input-elasticsearch/issues/85
