### ISSUE TITLE
Should run on a schedule

### ISSUE THREAD

**Issue by andrewvc** [logstash-plugins/logstash-input-elasticsearch#88]
This plugin should run on a schedule like the JDBC input, using cron syntax.

/cc @ctindel

**Comment by wols** [comment]
I see any 'schedule forks' and I'm not deep in `rufus/scheduler` but I have been using the [logstash-input-http_poller](https://github.com/logstash-plugins/logstash-input-http_poller) for a long time.
Is it perhaps a suitable model for the schedule option?

**Comment by andrewvc** [comment]
The plugin to copy would be the JDBC input in terms of scheduling options
(which I believe is quite similar).

We'd be glad to receive a patch along those lines! (With tests)

**Comment by ycombinator** [comment]
Is this a duplicate of https://github.com/logstash-plugins/logstash-input-elasticsearch/issues/32?

**Comment by simianhacker** [comment]
Too bad this doesn't exist... I would dog food the crap out of this and use it for all of my data collection needs.

**Comment by jsvd** [comment]
btw there's already a PR that implements this https://github.com/logstash-plugins/logstash-input-elasticsearch/pull/81/ I'll review it this week

**Comment by jsvd** [comment]
implemented in #81

**Comment by jsvd** [comment]
support for cron-like scheduling released in version 4.2.0 👍
